# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://conda.anaconda.org/conda-forge/linux-64/alabaster-0.7.10-py27_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/argtable2-2.13-1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/asn1crypto-0.22.0-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/aubio-0.4.5-np112py27_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/audioread-2.1.4-py27_2.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/babel-2.4.0-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/backports-1.0-py27_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/backports.functools_lru_cache-1.4-py27_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/backports.shutil_get_terminal_size-1.0.0-py_3.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/backports.weakref-1.0rc1-py27_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/backports_abc-0.5-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/blas-1.1-openblas.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/bleach-1.5.0-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/bzip2-1.0.6-1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ca-certificates-2017.7.27.1-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/certifi-2017.7.27.1-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/cffi-1.10.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/chardet-3.0.4-py27_0.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/conda-4.3.30-py27h6ae6dc7_0.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/conda-env-2.6.0-h36134e3_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/configparser-3.5.0-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/cryptography-2.0.3-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/cycler-0.10.0-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/dbus-1.10.22-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/decorator-4.1.2-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/docutils-0.14-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/eigen-3.3.3-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/entrypoints-0.2.3-py27_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/enum34-1.1.6-py27_1.tar.bz2
https://conda.anaconda.org/thomasfillon/linux-64/essentia-2.1_beta4-py27hf6fdc9d_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/expat-2.2.1-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ffmpeg-2.8.6-5.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/fftw-3.3.6-3.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/fontconfig-2.12.1-4.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/freetype-2.7-1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/funcsigs-1.0.2-py_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/functools32-3.2.3.2-py27_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/gdbm-1.12-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/gettext-0.19.7-1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/glib-2.53.5-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/gmp-6.1.2-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/gst-plugins-base-1.8.0-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/gstreamer-1.8.0-1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/h5py-2.7.1-py27_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/hdf5-1.8.18-1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/html5lib-0.9999999-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/icu-58.1-1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/idna-2.6-py27_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/imagesize-0.7.1-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/ipaddress-1.0.18-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/ipykernel-4.6.1-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ipython-5.5.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/ipython_genutils-0.2.0-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/ipywidgets-7.0.1-py_2.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/jinja2-2.9.6-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/joblib-0.11-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/jpeg-9b-1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/jsonschema-2.6.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/jupyter-1.0.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/jupyter_client-5.1.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/jupyter_console-5.1.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/jupyter_core-4.3.0-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/lapack-3.6.1-1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libffi-3.2.1-3.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libflac-1.3.1-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/libgcc-5.2.0-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/libgfortran-3.0.0-1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libiconv-1.14-4.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libogg-1.3.2-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libpng-1.6.28-1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/libprotobuf-3.4.0-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/librosa-0.5.1-py27_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libsndfile-1.0.27-1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/libsodium-1.0.10-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libtiff-4.0.7-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libvorbis-1.3.5-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/libxcb-1.12-1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/libxml2-2.9.5-0.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/llvmlite-0.20.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/lzo-2.06-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/markdown-2.6.9-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/markupsafe-1.0-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/matplotlib-2.1.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/mistune-0.7.4-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/mock-2.0.0-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/mpg123-1.24.0-1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/mysql-python-1.2.5-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/nbconvert-5.3.1-py_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/nbformat-4.4.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/ncurses-5.9-10.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/networkx-1.11-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/notebook-5.1.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/numba-0.35.0-np112py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/numexpr-2.6.4-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/numpy-1.12.1-py27_blas_openblas_200.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/olefile-0.44-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/openblas-0.2.19-2.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/openssl-1.0.2l-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pandas-0.20.3-py27_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pandoc-1.19.2-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pandocfilters-1.4.1-py27_0.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/path.py-10.3.1-py27hc258cac_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pathlib2-2.3.0-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pbr-3.1.1-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pcre-8.39-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pexpect-4.2.1-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pickleshare-0.7.4-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pillow-4.2.1-py27_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pip-9.0.1-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/prompt_toolkit-1.0.15-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/protobuf-3.4.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/ptyprocess-0.5.2-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pyasn1-0.2.3-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pycosat-0.6.1-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pycparser-2.18-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pycrypto-2.6.1-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pygments-2.2.0-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pyopenssl-17.2.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pyparsing-2.2.0-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pyqt-5.6.0-py27_4.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pysocks-1.6.7-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pytables-3.4.2-np112py27_3.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/python-2.7.13-1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/python-dateutil-2.6.1-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pytz-2017.2-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pyyaml-3.12-py27_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/pyzmq-16.0.2-py27_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/qt-5.6.2-3.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/qtconsole-4.3.1-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/readline-6.2-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/redis-3.2.0-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/requests-2.18.4-py27_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/resampy-0.2.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/ruamel_yaml-0.11.14-py27_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/scandir-1.6-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/scikit-learn-0.19.0-py27_blas_openblas_201.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/scipy-0.19.1-py27_blas_openblas_202.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/setuptools-36.3.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/simplegeneric-0.8.1-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/simplejson-3.11.1-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/singledispatch-3.4.0.3-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/sip-4.18-py27_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/six-1.11.0-py27_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/snowballstemmer-1.2.1-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/sphinx-1.6.4-py27_0.tar.bz2
https://repo.continuum.io/pkgs/main/linux-64/sphinxcontrib-1.0-py27h1512b58_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/sphinxcontrib-websupport-1.0.1-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/sqlite-3.13.0-1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/ssl_match_hostname-3.5.0.1-py27_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/subprocess32-3.2.7-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/tensorflow-1.3.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/terminado-0.6-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/testpath-0.3.1-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/tk-8.5.19-2.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/tornado-4.5.2-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/traitlets-4.3.2-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/traits-4.6.0-py27_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/typing-3.6.2-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/urllib3-1.22-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/wcwidth-0.1.7-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/webencodings-0.5-py27_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/werkzeug-0.12.2-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/wheel-0.30.0-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/widgetsnbextension-3.0.3-py27_2.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/x264-20131217-3.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libxau-1.0.8-3.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/xorg-libxdmcp-1.1.2-3.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/xz-5.2.3-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/yaafe-0.70-py27_2.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/yaml-0.1.6-0.tar.bz2
https://conda.anaconda.org/conda-forge/linux-64/zeromq-4.2.1-1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/zlib-1.2.8-3.tar.bz2
